/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class FrmInicio extends javax.swing.JFrame implements ActionListener{
    
    PnPresentacion pnPresent = new PnPresentacion();
    
    public FrmInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        FrmLoguin log = new FrmLoguin();
        lblDUI.setText(log.DUI);
        
        //this.pnPrincipal.add(pnPresent);
        
        this.btnCuentas.addActionListener(this);
        this.btnAbonos.addActionListener(this);
    }
        
    private void Cerrar() {

        String botones[] = {"Cerrar", "Cancelar"};
        int opcion = JOptionPane.showOptionDialog(this, "¿Estás seguro que quieres salir?", "Confirmar", 0, 0, null, botones, this);

        if (opcion == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (opcion == JOptionPane.NO_OPTION) {
            System.out.println("¡Cancelado!");
        }
    }

    private void CerrarSesion() {

        String botones[] = {"Salir", "Cancelar"};
        int opcion = JOptionPane.showOptionDialog(this, "¿Estás seguro que quieres cerrar sesión?", "Confirmar", 0, 0, null, botones, this);

        if (opcion == JOptionPane.YES_OPTION) {
            FrmLoguin logout = new FrmLoguin();
            logout.setVisible(true);
            this.dispose();
        } else if (opcion == JOptionPane.NO_OPTION) {
            System.out.println("¡Cancelado!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPrincipal = new javax.swing.JPanel();
        pnIzquierdo = new javax.swing.JPanel();
        lblImagen = new javax.swing.JLabel();
        lblTextDUI = new javax.swing.JLabel();
        lblDUI = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnCuentas = new javax.swing.JButton();
        btnAbonos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(825, 493));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnPrincipal.setBackground(new java.awt.Color(15, 47, 105));
        pnPrincipal.setMinimumSize(new java.awt.Dimension(764, 493));
        pnPrincipal.setLayout(new java.awt.BorderLayout());

        pnIzquierdo.setBackground(new java.awt.Color(10, 31, 70));

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/account.png"))); // NOI18N

        lblTextDUI.setBackground(new java.awt.Color(255, 255, 255));
        lblTextDUI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTextDUI.setForeground(new java.awt.Color(255, 255, 255));
        lblTextDUI.setText("DUI:");

        lblDUI.setBackground(new java.awt.Color(255, 255, 255));
        lblDUI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDUI.setForeground(new java.awt.Color(255, 255, 255));
        lblDUI.setText("00000000-0");

        btnCerrarSesion.setBackground(new java.awt.Color(212, 55, 51));
        btnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/exit.png"))); // NOI18N
        btnCerrarSesion.setText("        Cerrar Sesión");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setDefaultCapable(false);
        btnCerrarSesion.setFocusable(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        btnCuentas.setBackground(new java.awt.Color(10, 31, 70));
        btnCuentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCuentas.setForeground(new java.awt.Color(225, 225, 225));
        btnCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/money.png"))); // NOI18N
        btnCuentas.setText("        Cuentas");
        btnCuentas.setBorder(null);
        btnCuentas.setBorderPainted(false);
        btnCuentas.setDefaultCapable(false);
        btnCuentas.setFocusPainted(false);
        btnCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuentasActionPerformed(evt);
            }
        });

        btnAbonos.setBackground(new java.awt.Color(10, 31, 70));
        btnAbonos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAbonos.setForeground(new java.awt.Color(225, 225, 225));
        btnAbonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/arrow.png"))); // NOI18N
        btnAbonos.setText("        Abonos");
        btnAbonos.setBorder(null);
        btnAbonos.setBorderPainted(false);
        btnAbonos.setDefaultCapable(false);
        btnAbonos.setFocusPainted(false);

        javax.swing.GroupLayout pnIzquierdoLayout = new javax.swing.GroupLayout(pnIzquierdo);
        pnIzquierdo.setLayout(pnIzquierdoLayout);
        pnIzquierdoLayout.setHorizontalGroup(
            pnIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIzquierdoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(pnIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextDUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDUI)
                .addContainerGap())
            .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCuentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAbonos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnIzquierdoLayout.setVerticalGroup(
            pnIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnIzquierdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnIzquierdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextDUI)
                    .addComponent(lblDUI))
                .addGap(30, 30, 30)
                .addComponent(btnCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(btnCerrarSesion)
                .addGap(25, 25, 25))
        );

        btnCerrarSesion.getAccessibleContext().setAccessibleName("Cerrar Sesión");

        pnPrincipal.add(pnIzquierdo, java.awt.BorderLayout.WEST);

        getContentPane().add(pnPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        CerrarSesion();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuentasActionPerformed
        
    }//GEN-LAST:event_btnCuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCuentas;
    private javax.swing.JLabel lblDUI;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblTextDUI;
    private javax.swing.JPanel pnIzquierdo;
    private javax.swing.JPanel pnPrincipal;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        
        Object evt = e.getSource();
        
        pnPresent.setVisible(true);
        if(evt.equals(btnCuentas)){
            pnPrincipal.add(pnPresent);
            pnPrincipal.validate();
        }
    }
}
